import { type IconType } from "react-icons"
import {
  SiPython,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiNumpy,
  SiPandas,
  SiDocker,
  SiKubernetes,
  SiPostgresql,
  SiFastapi,
  SiJavascript,
  SiTypescript,
  SiCplusplus,
  SiNodedotjs,
  SiGit,
  SiLinux,
  SiJenkins,
  SiGooglecloud,
  SiApachespark,
  SiOpenai,
  SiGnubash,
  SiReact,
  SiYoutube,
  SiApachehive,
  SiGo,
  SiRedis,
  SiMongodb,
  SiApachekafka,
  SiApacheairflow,
  SiPrometheus,
  SiGrafana,
  SiMlflow,
  SiHuggingface,
  SiOnnx,
  SiGithubactions,
  SiAnthropic,
} from "react-icons/si"
import { FaAws, FaChartBar } from "react-icons/fa"

export interface TechEntry {
  icon: IconType
  color: string
}

const map: Record<string, TechEntry> = {
  python: { icon: SiPython, color: "#3776AB" },
  pytorch: { icon: SiPytorch, color: "#EE4C2C" },
  tensorflow: { icon: SiTensorflow, color: "#FF6F00" },
  "scikit-learn": { icon: SiScikitlearn, color: "#F7931E" },
  numpy: { icon: SiNumpy, color: "#013243" },
  pandas: { icon: SiPandas, color: "#150458" },
  docker: { icon: SiDocker, color: "#2496ED" },
  kubernetes: { icon: SiKubernetes, color: "#326CE5" },
  postgresql: { icon: SiPostgresql, color: "#4169E1" },
  postgres: { icon: SiPostgresql, color: "#4169E1" },
  fastapi: { icon: SiFastapi, color: "#009688" },
  javascript: { icon: SiJavascript, color: "#F7DF1E" },
  typescript: { icon: SiTypescript, color: "#3178C6" },
  "c++": { icon: SiCplusplus, color: "#00599C" },
  "node.js": { icon: SiNodedotjs, color: "#5FA04E" },
  git: { icon: SiGit, color: "#F05032" },
  linux: { icon: SiLinux, color: "#FCC624" },
  jenkins: { icon: SiJenkins, color: "#D24939" },
  gcp: { icon: SiGooglecloud, color: "#4285F4" },
  spark: { icon: SiApachespark, color: "#E25A1C" },
  pyspark: { icon: SiApachespark, color: "#E25A1C" },
  tableau: { icon: FaChartBar, color: "#E97627" },
  openai: { icon: SiOpenai, color: "#412991" },
  gpt: { icon: SiOpenai, color: "#412991" },
  "gpt-4o-mini": { icon: SiOpenai, color: "#412991" },
  bash: { icon: SiGnubash, color: "#4EAA25" },
  react: { icon: SiReact, color: "#61DAFB" },
  "youtube api": { icon: SiYoutube, color: "#FF0000" },
  aws: { icon: FaAws, color: "#FF9900" },
  "aws ec2": { icon: FaAws, color: "#FF9900" },
  ec2: { icon: FaAws, color: "#FF9900" },
  s3: { icon: FaAws, color: "#FF9900" },
  lambda: { icon: FaAws, color: "#FF9900" },
  sagemaker: { icon: FaAws, color: "#FF9900" },
  "aws sagemaker": { icon: FaAws, color: "#FF9900" },
  "aws glue": { icon: FaAws, color: "#FF9900" },
  athena: { icon: FaAws, color: "#FF9900" },
  "hive sql": { icon: SiApachehive, color: "#FDEE21" },
  go: { icon: SiGo, color: "#00ADD8" },
  redis: { icon: SiRedis, color: "#DC382D" },
  mongodb: { icon: SiMongodb, color: "#47A248" },
  kafka: { icon: SiApachekafka, color: "#231F20" },
  airflow: { icon: SiApacheairflow, color: "#017CEE" },
  prometheus: { icon: SiPrometheus, color: "#E6522C" },
  grafana: { icon: SiGrafana, color: "#F46800" },
  mlflow: { icon: SiMlflow, color: "#0194E2" },
  "hugging face": { icon: SiHuggingface, color: "#FFD21E" },
  huggingface: { icon: SiHuggingface, color: "#FFD21E" },
  "onnx runtime": { icon: SiOnnx, color: "#005CED" },
  onnx: { icon: SiOnnx, color: "#005CED" },
  "github actions": { icon: SiGithubactions, color: "#2088FF" },
  bedrock: { icon: FaAws, color: "#FF9900" },
  "aws bedrock": { icon: FaAws, color: "#FF9900" },
  claude: { icon: SiAnthropic, color: "#D97757" },
  "claude code": { icon: SiAnthropic, color: "#D97757" },
  anthropic: { icon: SiAnthropic, color: "#D97757" },
}

export function getTechIcon(name: string): TechEntry | null {
  return map[name.toLowerCase()] ?? null
}

export const marqueeTechs: { name: string; icon: IconType; color: string }[] = [
  { name: "Python", icon: SiPython, color: "#3776AB" },
  { name: "PyTorch", icon: SiPytorch, color: "#EE4C2C" },
  { name: "TensorFlow", icon: SiTensorflow, color: "#FF6F00" },
  { name: "OpenAI", icon: SiOpenai, color: "#412991" },
  { name: "scikit-learn", icon: SiScikitlearn, color: "#F7931E" },
  { name: "Docker", icon: SiDocker, color: "#2496ED" },
  { name: "Kubernetes", icon: SiKubernetes, color: "#326CE5" },
  { name: "AWS", icon: FaAws, color: "#FF9900" },
  { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  { name: "FastAPI", icon: SiFastapi, color: "#009688" },
  { name: "React", icon: SiReact, color: "#61DAFB" },
  { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  { name: "GCP", icon: SiGooglecloud, color: "#4285F4" },
  { name: "Jenkins", icon: SiJenkins, color: "#D24939" },
  { name: "Spark", icon: SiApachespark, color: "#E25A1C" },
  { name: "Node.js", icon: SiNodedotjs, color: "#5FA04E" },
  { name: "NumPy", icon: SiNumpy, color: "#013243" },
  { name: "Pandas", icon: SiPandas, color: "#150458" },
  { name: "Git", icon: SiGit, color: "#F05032" },
  { name: "Linux", icon: SiLinux, color: "#FCC624" },
  { name: "Tableau", icon: FaChartBar, color: "#E97627" },
  { name: "Bash", icon: SiGnubash, color: "#4EAA25" },
  { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  { name: "C++", icon: SiCplusplus, color: "#00599C" },
  { name: "Go", icon: SiGo, color: "#00ADD8" },
  { name: "Redis", icon: SiRedis, color: "#DC382D" },
  { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  { name: "Kafka", icon: SiApachekafka, color: "#231F20" },
  { name: "Airflow", icon: SiApacheairflow, color: "#017CEE" },
  { name: "Prometheus", icon: SiPrometheus, color: "#E6522C" },
  { name: "Grafana", icon: SiGrafana, color: "#F46800" },
  { name: "MLflow", icon: SiMlflow, color: "#0194E2" },
  { name: "Hugging Face", icon: SiHuggingface, color: "#FFD21E" },
  { name: "ONNX", icon: SiOnnx, color: "#005CED" },
  { name: "GitHub Actions", icon: SiGithubactions, color: "#2088FF" },
  { name: "Claude", icon: SiAnthropic, color: "#D97757" },
]
